# Generated by Django 4.0.3 on 2022-03-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='weather_celcius',
            field=models.IntegerField(default=0, verbose_name='weather_celsius'),
        ),
    ]
